"""YouTube publishing guide: step-by-step upload instructions and both descriptions.

Usage: uv run python src/youtube.py workspace/tmp/events_landscape.json workspace/tmp/events_portrait.json
Prints Markdown, which render.sh saves as youtube-publishing.md: how to upload the full video, then
the Short (which links to it), then link them both ways, then the repo follow-ups; followed by the
two descriptions to paste. Chapter timestamps (one per section, the first starting at 0:00 so the
title card is part of it) come from the render, so they always match the video. Edit the text below.
Fails if the chapters break YouTube's rules (first at 0:00, at least 3, each at least 10 seconds),
since YouTube would then show none.
The published video and Short URLs are left as placeholders to fill in at upload time.
"""
import json
import sys

NAME = "jev-vs-llm"
REPO = f"https://github.com/sujee/visual-explainers/tree/main/explainers/{NAME}"
SOURCE = "https://typesafe.ai/blog/introducing-system-one-models-and-jev"
PLAYLIST = "Visual Explainers"

TITLE = "Jev vs. LLMs: a model that decides instead of writing | Explainer Video"
SHORT_TITLE = "Most AI models write. Jev decides. #Shorts"
# The first three hashtags show above the title on YouTube; keep the total well under 15.
HASHTAGS = "#AI #LLM #ExplainerVideo #Jev"
SHORT_HASHTAGS = "#Shorts #AI #LLM #Jev #ExplainerVideo"
# Studio's Tags box (Show more): comma-separated, under 500 characters in total.
TAGS = ("Jev, TypeSafe AI, System One model, LLM, large language model, AI explained, explainer video, "
        "calibrated probabilities, RLCD, RLHF, structured output, AI automation, machine learning, "
        "Jev vs LLM, AI for developers")

ABOUT = """\
Most AI models write their answers. Jev, TypeSafe AI's new "System One" model, doesn't write at all: it reads \
your program's state and returns typed decisions, with a calibrated probability for every option. This \
explainer shows what that means for developers: why it's fast, how to act on its confidence, and where an LLM \
is still the right tool."""

NOTES = f"""\
Facts and performance figures are TypeSafe AI's own, from its launch post (September 2026): {SOURCE}
They are the company's benchmarks; no independent evaluation had been published at the time of making.
Probabilities and counts shown on screen are illustrative.

Source, brief and how to reproduce or remix it: {REPO}
Video and music: CC BY 4.0. Code: Apache-2.0.

Created by sujee.dev

{HASHTAGS}"""

SHORT = f"""\
Most AI models write. Jev doesn't: it picks from the answers you define, with a probability for each, in one pass.

Full 2-minute explainer: <insert link to the full video>
Facts from TypeSafe AI's launch post: {SOURCE}

Created by sujee.dev

{SHORT_HASHTAGS}"""


def stamp(t):
    t = int(t)   # floor: the chapter starts at or just before its title card
    return f"{t // 60}:{t % 60:02d}"


land = json.load(open(sys.argv[1]))
short = json.load(open(sys.argv[2]))
chapters = [[t, title] for t, title in land.get("chapters", [])]
if chapters:
    chapters[0][0] = 0.0   # the title card belongs to the first chapter
ends = [t for t, _ in chapters[1:]] + [land["end"]]
problems = []
if len(chapters) < 3:
    problems.append(f"only {len(chapters)} chapters (YouTube needs at least 3)")
for (t, title), e in zip(chapters, ends):
    if int(e) - int(t) < 10:
        problems.append(f"chapter '{title}' at {stamp(t)} is {e - t:.1f} s (YouTube needs at least 10 s)")
if problems:
    sys.exit("youtube.py: chapters would be ignored by YouTube:\n  " + "\n  ".join(problems))

video = f"workspace/preview/<version>/{NAME}-<version>"
print(f"""# Publishing on YouTube: Jev vs. LLM

Generated by render.sh from the render's own timeline: edit `src/youtube.py`, not this file (a render overwrites it).
Upload the full video first, because the Short links to it.

## 1. Upload the full video ({stamp(land['end'])})

1. In YouTube Studio, choose **Create → Upload videos** and pick
   `{video}-16x9-4k.mp4` (the version with music).
2. **Title:** `{TITLE}`
3. **Description:** paste the "Full video description" below. The chapters appear automatically.
4. **Thumbnail:** upload one of `thumbnails/{NAME}-thumbnail-{{a,b,c}}-16x9.png`.
5. **Playlist:** {PLAYLIST}.
6. **Audience:** No, it's not made for kids.
7. **Show more:** License **Creative Commons – Attribution**; Category **Science & Technology**;
   Altered or synthetic content **No** (animated explainer, nothing realistic);
   **Tags:** `{TAGS}`.
8. **Visibility:** Public (or Unlisted to check it first). Publish.
9. **Copy the video's URL:** the Short needs it. Once the Short is up, come back and replace
   `<insert link to the Short>` in this description (step 3).

## 2. Upload the Short ({stamp(short['end'])})

1. Upload `{video}-9x16-4k.mp4`. It's vertical and under 3 minutes, so YouTube treats it as a Short.
2. **Title:** `{SHORT_TITLE}`
3. **Description:** paste the "Short description" below, with the full video's URL in place of `<insert link to the full video>`.
4. **Related video:** set it to the full video, so viewers can tap through from the Short.
5. **Thumbnail:** if your YouTube app offers a custom Short thumbnail, use
   `thumbnails/{NAME}-thumbnail-a-9x16.png`; otherwise pick a frame from the hook.
6. Same playlist, audience, license, category and tags as the full video. Publish.

## 3. Link them both ways

- On the full video, make sure the description's "Short version" line has the Short's URL, and pin a comment: "The {int(short['end'])}-second version: <insert link to the Short>".
- Optional: on the full video, add an end screen element pointing to the Short or the playlist.

## 4. Back in the repo

- `README.md`: replace "coming soon" with the video and Short links.
- Root `README.md`: add a row to the Explainers table.
- A GitHub release `{NAME}-v1` with the four 4K masters from `workspace/preview/<version>/`, linked from both READMEs.

---

## Full video description

```text
{ABOUT}

Short version ({int(short['end'])} s): <insert link to the Short>

Chapters""")
for t, title in chapters:
    print(f"{stamp(t)} {title}")
print(f"""
{NOTES}
```

## Short description

```text
{SHORT}
```""")
